import { Status } from "@/pages/bill/bill-tab/history";
import {
  PACKAGE_STATUS_ARCHIVED,
  PACKAGE_STATUS_ARCHIVED_TEXT,
  PACKAGE_STATUS_CANCELLED,
  PACKAGE_STATUS_CANCELLED_TEXT,
  PACKAGE_STATUS_CREATED,
  PACKAGE_STATUS_CREATED_TEXT,
  PACKAGE_STATUS_DELIVERED,
  PACKAGE_STATUS_DELIVERED_TEXT,
  PACKAGE_STATUS_EXPIRED,
  PACKAGE_STATUS_EXPIRED_TEXT,
  PACKAGE_STATUS_IN_TRANSIT,
  PACKAGE_STATUS_IN_TRANSIT_TEXT,
  PACKAGE_STATUS_PENDING_PICKUP,
  PACKAGE_STATUS_PENDING_PICKUP_TEXT,
  PACKAGE_STATUS_PICKED,
  PACKAGE_STATUS_RE_PENDING_PICKUP,
  PACKAGE_STATUS_UNDELIVERED,
  PACKAGE_STATUS_UNDELIVERED_TEXT,
  PACKAGE_STATUS_WAREHOUSE_EXPORT,
  PACKAGE_STATUS_WAREHOUSE_IN_CONTAINER,
  PACKAGE_STATUS_WAREHOUSE_IN_SHIPMENT,
  PACKAGE_STATUS_WAREHOUSE_LABELED,
} from "../packages";

export const MAP_SHIPMENT_STATUS: Status = {
  [PACKAGE_STATUS_CREATED]: {
    text: PACKAGE_STATUS_CREATED_TEXT,
    className: "await",
  },
  [PACKAGE_STATUS_PENDING_PICKUP]: {
    text: PACKAGE_STATUS_PENDING_PICKUP_TEXT,
    className: "pending",
  },
  [PACKAGE_STATUS_RE_PENDING_PICKUP]: {
    text: PACKAGE_STATUS_PENDING_PICKUP_TEXT,
    className: "pending",
  },
  [PACKAGE_STATUS_PICKED]: {
    text: PACKAGE_STATUS_IN_TRANSIT_TEXT,
    className: "text-[#13c2c2] bg-[#e6fffb]",
  },
  [PACKAGE_STATUS_WAREHOUSE_LABELED]: {
    text: PACKAGE_STATUS_IN_TRANSIT_TEXT,
    className: "text-[#13c2c2] bg-[#e6fffb]",
  },
  [PACKAGE_STATUS_WAREHOUSE_IN_CONTAINER]: {
    text: PACKAGE_STATUS_IN_TRANSIT_TEXT,
    className: "text-[#13c2c2] bg-[#e6fffb]",
  },
  [PACKAGE_STATUS_WAREHOUSE_IN_SHIPMENT]: {
    text: PACKAGE_STATUS_IN_TRANSIT_TEXT,
    className: "text-[#13c2c2] bg-[#e6fffb]",
  },
  [PACKAGE_STATUS_WAREHOUSE_EXPORT]: {
    text: PACKAGE_STATUS_IN_TRANSIT_TEXT,
    className: "text-[#13c2c2] bg-[#e6fffb]",
  },
  [PACKAGE_STATUS_IN_TRANSIT]: {
    text: PACKAGE_STATUS_IN_TRANSIT_TEXT,
    className: "text-[#13c2c2] bg-[#e6fffb]",
  },
  [PACKAGE_STATUS_DELIVERED]: {
    text: PACKAGE_STATUS_DELIVERED_TEXT,
    className: "success",
  },
  [PACKAGE_STATUS_CANCELLED]: {
    text: PACKAGE_STATUS_CANCELLED_TEXT,
    className: "danger",
  },
  [PACKAGE_STATUS_EXPIRED]: {
    text: PACKAGE_STATUS_EXPIRED_TEXT,
    className: "expired",
  },
  [PACKAGE_STATUS_UNDELIVERED]: {
    text: PACKAGE_STATUS_UNDELIVERED_TEXT,
    className: "danger",
  },
  [PACKAGE_STATUS_ARCHIVED]: {
    text: PACKAGE_STATUS_ARCHIVED_TEXT,
    className: "text-[#f5222d] bg-[#fff1f0]",
  },
};

export enum ContainerType {
  Ups = 1,
  Manual = 2,
  FedEx = 3,
}
