name: Build App

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          npx vite build
        
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          